### ISSUE TITLE
iCloud Drive icon stays blank

### ISSUE THREAD

**Issue by frac89** [w0lfschild/colorfulSidebar_9#14] opened 2020-03-26 07:02 UTC
As the title says.

![Schermata 2020-03-26 alle 08 01 20](https://user-images.githubusercontent.com/32241124/77619200-01f66c80-6f38-11ea-8cc0-4cd3660c95db.png)

**Comment by w0lfschild** [comment] 2020-03-26 19:33
What version of macOS? 

It does look like the icon is being themed, just not correctly, since that's the default Document icon.

**Comment by frac89** [comment] 2020-03-26 19:36
I use Mojave. I tried to add some paths to iCloud Drive (Like the one of MobileDocuments) to no avail.

**Comment by w0lfschild** [comment] 2020-03-26 19:44
In `icons14.plist` edit the array 

`/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/iDiskGenericIcon.icns`

and add the string

`iCloud Drive` 

![Screen Shot 2020-03-26 at 12 41 46 PM](https://user-images.githubusercontent.com/1920148/77689686-53feb880-6f5f-11ea-8bf6-f2f075c28303.png)

**Comment by frac89** [comment] 2020-03-26 19:51
Still nothing, that's strange because before version 2 it used to work flawlessly.

**Comment by w0lfschild** [comment] 2020-03-26 20:05
Did you restart Finder after making the changes?

**Comment by frac89** [comment] 2020-03-26 20:06
Yes I did.

**Comment by QrchackOfficial** [comment] 2020-03-28 13:17
I can confirm this on 10.14.6 Mojave as well. I suspect the "address" with the `x-applefinder-vnode` part is not being picked up for some reason, so there's a generic icon instead. Same goes for Tags, how do we address those?

See here (Favourites are set to black on purpose, I'm using colorfulSidebar to change symlinks on ~/Movies and ~/Music from generic folder icons to the proper ones). Tags and iCloud Drive are not set. For iCloud Drive, I have:

- `cmdGoToICloud`
- `x-applefinder-vnode:iCloud%20Drive`
- `x-applefinder-vnode:iCloud`

`x-applefinder-vnode:iCloud Drive` also wouldn't work. Moving the icon in Finder to Favourites also didn't change anything.

![image](https://user-images.githubusercontent.com/3584315/77823818-564b4900-70fe-11ea-8dc5-c6ae273fb3fc.png)

Is this a problem with the string in .plist, or do we need to update code to get that to work?

**Comment by QrchackOfficial** [comment] 2020-03-28 13:22
This *might* be due to AMFI enabled, I'm on a Hackintosh here, so a bit nervous about adding `nvram boot-args`, but I'll test if I can get Clover to disable AMFI

**Comment by frac89** [comment] 2020-03-28 16:45
I tried to disable AMFI, but it still remains blank. Also disabling AMFI makes it so I can't give permissions to apps to use my camera/microphone or other apps for reasons unknown to me.

**Comment by w0lfschild** [comment] 2020-03-28 22:28
It doesn't have to do with AMFI. PS if you have AMFI off read this > https://www.reddit.com/r/OSXTweaks/comments/fpes5q/unable_to_launch_xtrafinder_in_mojave/flksmhi?utm_source=share&utm_medium=web2x

If you delete this from the .plist does the issue persist?
```
<key>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/GenericDocumentIcon.icns</key>
<array>
	<string>SidebarGenericFile</string>
</array>
```

**Comment by QrchackOfficial** [comment] 2020-03-28 22:49
It wasn't there from the beginning. I have cleared the plist out, so the only overrides are set explicitly by me. Therefore, no generic/smart folder/NS* entries.

**Comment by QrchackOfficial** [comment] 2020-03-28 22:53
My current plist looks like so:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/iDiskGenericIcon.icns</key>
	<array>
		<string>iCloud Drive</string>
		<string>cmdGoToICloud</string>
		<string>x-applefinder-vnode:iCloud%20Drive</string>
		<string>x-applefinder-vnode:CloudDocs%20libraries</string>
		<string>x-applefinder-vnode:iCloud</string>
	</array>
	<key>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarMoviesFolder.icns</key>
	<array>
		<string>~/Movies</string>
		<string>/Volumes/Data/Movies</string>
	</array>
	<key>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarHomeFolder.icns</key>
	<array>
		<string>~/</string>
	</array>
	<key>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarPicturesFolder.icns</key>
	<array>
		<string>~/Pictures</string>
	</array>
	<key>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarMusicFolder.icns</key>
	<array>
		<string>~/Music</string>
		<string>/Volumes/Data/Music</string>
	</array>
	<key>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarDocumentsFolder.icns</key>
	<array>
		<string>~/Documents</string>
	</array>
	<key>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarDesktopFolder.icns</key>
	<array>
		<string>~/Desktop</string>
	</array>
	<key>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarDownloadsFolder.icns</key>
	<array>
		<string>~/Downloads</string>
	</array>
	<key>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarApplicationsFolder.icns</key>
	<array>
		<string>/Applications</string>
	</array>
</dict>
</plist>
```

**Comment by frac89** [comment] 2020-03-29 00:46
> It doesn't have to do with AMFI. PS if you have AMFI off read this > https://www.reddit.com/r/OSXTweaks/comments/fpes5q/unable_to_launch_xtrafinder_in_mojave/flksmhi?utm_source=share&utm_medium=web2x
> 
> If you delete this from the .plist does the issue persist?
> 
> ```
> <key>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/GenericDocumentIcon.icns</key>
> <array>
> 	<string>SidebarGenericFile</string>
> </array>
> ```

Thanks for the AMFI tip, I'll make sure to try it.

Anyway, the iCloud icon still stays blank.

**Comment by qkdreyer** [comment] 2020-04-03 08:21
Not having any issues with iCloud Drive using macOS Catalina 10.15 (19A582a) here.
Thanks for the 2.0.1 update @w0lfschild btw, the previous NSLog were frustrating :)

**Comment by cryo-kronos** [comment] 2020-04-03 18:00
iCloud icon is blank for me on macOS Mojave 10.14.6.

**Comment by w0lfschild** [comment] 2020-04-22 03:03
Okay think I've got a fix for this ready to go out soon.

**Comment by w0lfschild** [comment] 2020-04-22 05:45
Fix should be live now. Version 2.0.3

**Closed as completed by w0lfschild** 2020-04-22 05:45 UTC
